sudo: required
services: docker
script:
  # We use the docker image from https://hub.docker.com/r/cludch/tectonic/
  - docker pull cludch/tectonic
  - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind cludch/tectonic tectonic VD.tex
